# Site settings
title: прочтено
tag_text: прочтено
description: восторг, уныние, би
url: "http://prochteno.github.io"

font-awesome-include: false

markdown: kramdown
exclude: ["README.md", "LICENSE"]
